resource_group_name         = "rg_infra"
virtual_network_name        = "vnet002"
subnet_name                 = "subnet002"
public_ip_name              = "publicip002"
network_security_group_name = "nsg002"
network_interface_name      = "nic002"
windows_virtual_machine_name  = "windowsvm001"